### ISSUE TITLE
parse_time throws KeyError exception - sample included

### ISSUE THREAD

**Issue by savvopoulos** [FraBle/python-duckling#1]
Traceback (most recent call last):
  File "wtf.py", line 64, in <module>
    d.parse_time(b)
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 224, in parse_time
    return self._parse(input_str, dim=Dim.TIME)
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 41, in _parse
    input_str, self.language, dim_filter=dim)
  File "/usr/local/lib/python3.5/site-packages/duckling/duckling.py", line 106, in parse
    return self._parse_result(duckling_result)
  File "/usr/local/lib/python3.5/site-packages/duckling/duckling.py", line 124, in _parse_result
    field.getValue(), entry[u'dim'])
  File "/usr/local/lib/python3.5/site-packages/duckling/duckling.py", line 156, in _parse_dict
    result[key] = _functions[key](field.getValue())
KeyError: 'from'

For this python snippet:
```
import duckling
a="""
I was reading through your and others' recommendations and saw(for the first
time) your dinner invitation. Sorry for the delay. I need to take a rain
check. Life is really hectic right now. As you will note from the time, I am
here early just to clean out my e-mails--what has technology done to us. I am
in CA once a week. Yesterday, my 5 year old called me at the office at  7am
and asked me why I was never there when he woke up. So much for my cushy
in-house job. Anyway, a night away is too hard to find right now. What about
lunch? Thurs or Fri of next week?



	"Welsh, H. Ronald" <rwelsh@velaw.com>
	05/16/2001 06:26 PM

		 To: "'Richard.B.Sanders@enron.com'" <Richard.B.Sanders@enron.com>
		 cc:
		 Subject: RE: Trial Lawyer


Richard,

I know two top flight trial lawyers in New York:

Greg Joseph
Fried, Frank, Harris, Shriver, & Jacobson
One New York Plaza
New York, New York 10004
212-859-8584
josepgr@ffhsj.com


Norm Kleinberg
Hughes Hubbard & Reed LLP
One Battery Park Plaza
NY  10004
212-837-6680
kleinber@hugheshubbard.com


In addition, VE has a lateral partner whom I have not met:

James Serota
VE
NY
917-206-8004
jserota@velaw.com

Jamie's bio says that his area of practice is antitrust and business
litigation,particularly concentrated on industries
that are evolving from regulation to competition, including electric
utilities.  It says he chaired the Fuel and Energy Industry Committee of the
ABA Antitrust Section from 94-97.

When are you in town, so we can have dinner?

Ron
"""

d = duckling.DucklingWrapper()
d.parse_time(a)

```

**Comment by savvopoulos** [comment]
FYI works in clojure/duckling

({:dim :time, :body "Thurs", :value {:type "value", :value "2016-10-20T00:00:00.000+01:00", :grain :day, :values ({:type "value", :value "2016-10-20T00:00:00.000+01:00", :grain :day} {:type "value", :value "2016-10-27T00:00:00.000+01:00", :grain :day} {:type "value", :value "2016-11-03T00:00:00.000Z", :grain :day})}, :start 538, :end 543} {:dim :time, :body "right now", :value {:type "value", :value "2016-10-17T17:38:36.000+01:00", :grain :second, :values ({:type "value", :value "2016-10-17T17:38:36.000+01:00", :grain :second})}, :start 179, :end 188} {:dim :time, :body "right now", :value {:type "value", :value "2016-10-17T17:38:36.000+01:00", :grain :second, :values ({:type "value", :value "2016-10-17T17:38:36.000+01:00", :grain :second})}, :start 509, :end 518} {:dim :time, :body "Yesterday", :value {:type "value", :value "2016-10-16T00:00:00.000+01:00", :grain :day, :values ()}, :start 324, :end 333} {:dim :time, :body "night", :value {:type "interval", :from {:value "2016-10-17T18:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-18T00:00:00.000+01:00", :grain :hour}, :values ({:type "interval", :from {:value "2016-10-17T18:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-18T00:00:00.000+01:00", :grain :hour}} {:type "interval", :from {:value "2016-10-18T18:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-19T00:00:00.000+01:00", :grain :hour}} {:type "interval", :from {:value "2016-10-19T18:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-20T00:00:00.000+01:00", :grain :hour}})}, :start 478, :end 483, :latent true} {:dim :time, :body "lunch", :value {:type "interval", :from {:value "2016-10-18T12:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-18T14:00:00.000+01:00", :grain :hour}, :values ({:type "interval", :from {:value "2016-10-18T12:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-18T14:00:00.000+01:00", :grain :hour}} {:type "interval", :from {:value "2016-10-19T12:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-19T14:00:00.000+01:00", :grain :hour}} {:type "interval", :from {:value "2016-10-20T12:00:00.000+01:00", :grain :hour}, :to {:value "2016-10-20T14:00:00.000+01:00", :grain :hour}})}, :start 531, :end 536, :latent true} {:dim :time, :body "two", :value {:type "value", :value "2002-01-01T00:00:00.000Z", :grain :year, :values ()}, :start 761, :end 764, :latent true} {:dim :time, :body "One", :value {:type "value", :value "2001-01-01T00:00:00.000Z", :grain :year, :values ()}, :start 858, :end 861, :latent true} {:dim :time, :body "One", :value {:type "value", :value "2001-01-01T00:00:00.000Z", :grain :year, :values ()}, :start 976, :end 979, :latent true} {:dim :time, :body "212", :value {:type "value", :value "0212-01-01T00:00:00.000-00:01:15", :grain :year, :values ()}, :start 902, :end 905, :latent true} {:dim :time, :body "212", :value {:type "value", :value "0212-01-01T00:00:00.000-00:01:15", :grain :year, :values ()}, :start 1009, :end 1012, :latent true} {:dim :time, :body "917", :value {:type "value", :value "0917-01-01T00:00:00.000-00:01:15", :grain :year, :values ()}, :start 1130, :end 1133, :latent true} {:dim :time, :body "the first", :value {:type "value", :value "2016-11-01T00:00:00.000Z", :grain :day, :values ({:type "value", :value "2016-11-01T00:00:00.000Z", :grain :day} {:type "value", :value "2016-12-01T00:00:00.000Z", :grain :day} {:type "value", :value "2017-01-01T00:00:00.000Z", :grain :day})}, :start 67, :end 76} {:dim :time, :body "5", :value {:type "value", :value "2016-10-17T17:00:00.000+01:00", :grain :hour, :values ({:type "value", :value "2016-10-17T17:00:00.000+01:00", :grain :hour} {:type "value", :value "2016-10-18T05:00:00.000+01:00", :grain :hour} {:type "value", :value "2016-10-18T17:00:00.000+01:00", :grain :hour})}, :start 338, :end 339, :latent true} {:dim :time, :body "05/16/2001 06:26 PM", :value {:type "value", :value "2001-05-16T18:26:00.000+01:00", :grain :minute, :values ()}, :start 610, :end 629} {:dim :time, :body "Fri of next week", :value {:type "value", :value "2016-10-28T00:00:00.000+01:00", :grain :day, :values ({:type "value", :value "2016-10-28T00:00:00.000+01:00", :grain :day})}, :start 547, :end 563} {:dim :time, :body "-859", :value {:type "value", :value "2041-01-01T00:00:00.000Z", :grain :year, :values ({:type "value", :value "2041-01-01T00:00:00.000Z", :grain :year})}, :start 905, :end 909, :latent true} {:dim :time, :body "-8584", :value {:type "value", :value "2016-01-01T00:00:00.000Z", :grain :year, :values ({:type "value", :value "2016-01-01T00:00:00.000Z", :grain :year})}, :start 909, :end 914, :latent true} {:dim :time, :body "-837", :value {:type "value", :value "1963-01-01T00:00:00.000Z", :grain :year, :values ()}, :start 1012, :end 1016, :latent true} {:dim :time, :body "-6680", :value {:type "value", :value "2020-01-01T00:00:00.000Z", :grain :year, :values ({:type "value", :value "2020-01-01T00:00:00.000Z", :grain :year})}, :start 1016, :end 1021, :latent true} {:dim :time, :body "-206", :value {:type "value", :value "1994-01-01T00:00:00.000Z", :grain :year, :values ()}, :start 1133, :end 1137, :latent true} {:dim :time, :body "-8004", :value {:type "value", :value "1996-01-01T00:00:00.000Z", :grain :year, :values ()}, :start 1137, :end 1142, :latent true} {:dim :time, :body "from 94-97", :value {:type "interval", :from {:value "1994-01-01T00:00:00.000Z", :grain :year}, :to {:value "1998-01-01T00:00:00.000Z", :grain :year}, :values ()}, :start 1449, :end 1459} {:dim :time, :body "at  7am", :value {:type "value", :value "2016-10-18T07:00:00.000+01:00", :grain :hour, :values ({:type "value", :value "2016-10-18T07:00:00.000+01:00", :grain :hour} {:type "value", :value "2016-10-19T07:00:00.000+01:00", :grain :hour} {:type "value", :value "2016-10-20T07:00:00.000+01:00", :grain :hour})}, :start 373, :end 380})

**Comment by FraBle** [comment]
Hi Chris,

the problem was, that I missed the handling of intervals in time expressions.
In particular, the expression 'night' from your input letter would throw the error since instead of a simple entry for 'value' in 'value', Duckling returns two dicts for 'from' and 'to':

```
{
    :dim :time,
    :body "night",
    :value {
        :type "interval",
        :from {
            :value "2016-10-17T18:00:00.000+01:00",
            :grain :hour
        },
        :to {
            :value "2016-10-18T00:00:00.000+01:00",
            :grain :hour
        },
        :values (
            {
                :type "interval",
                :from {
                    :value "2016-10-17T18:00:00.000+01:00",
                    :grain :hour
                },
                :to {
                    :value "2016-10-18T00:00:00.000+01:00",
                    :grain :hour
                }
            }{
                :type "interval",
                :from {
                    :value "2016-10-18T18:00:00.000+01:00",
                    :grain :hour
                },
                :to {
                    :value "2016-10-19T00:00:00.000+01:00",
                    :grain :hour
                }
            }{
                :type "interval",
                :from {
                    :value "2016-10-19T18:00:00.000+01:00",
                    :grain :hour
                },
                :to {
                    :value "2016-10-20T00:00:00.000+01:00",
                    :grain :hour
                }
            }
        )
    },
    :start 478,
    :end 483,
    :latent true
}
```

It should be fixed now and I just pushed the latest version (v.1.1.3) to pypi 😋

**Comment by savvopoulos** [comment]
Amazing - thank you for fixing!

**Comment by savvopoulos** [comment]
Hmm, same issue with this snippet:
`import duckling

a = """
Kay -- Just some housekeeping questions:

Do you want hand-written or e-mail comments going forward?

Do you want more comments from Origination and Services now, or do you want
us to wait until you turn the doc?  As I said yesterday, I am in the process
of sorting out the "Costs" definition so that it works better with the other
parts of the doc.

MDEA is willing to extend the ILA two weeks if we want to.  Their next Board
meeting (after tonight's Board meeting) is June 12 , and they desperately
need to have our contract finished in time to get signing approval at that
meeting.  We probably need something to bridge us from the end of May until
their Board votes on the full agreement.  The other option is to get done
this week and have them call a special Board meeting.  They have done this in
the past, but we have not asked them if it's logistically possible to do this
by May 31.

Thanks -- David
"""

d = duckling.DucklingWrapper()
d.parse_time(a)
`

Stack trace:
`Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    d.parse_time(a)
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 247, in parse_time
    return self._parse(input_str, dim=Dim.TIME)
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 45, in _parse
    result_entry = self._dims[entry[u'dim']](entry)
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 90, in _parse_time
    return self._parse_interval(result_entry, duckling_result_entry)
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 75, in _parse_interval
    u'to': duckling_result_entry[u'value'][u'to'][u'value'],
KeyError: 'to'`

**Comment by savvopoulos** [comment]
Thanks. These Enron guys are still breaking things! :-D

**Comment by FraBle** [comment]
Alright, so this time, it's because Duckling detects 'after tonight' as an interval, but only gives a 'from' information, no 'to'. I fixed it and wrote a test, pushing it very soon.

**Comment by FraBle** [comment]
Ok, the build is green and the package is on pypi now (v1.1.4) ☺️

**Comment by FraBle** [comment]
@savvopoulos, can you confirm that it is working for you now?

**Comment by savvopoulos** [comment]
Hi Frank, yes I can confirm.

I ran it on 1k emails from the Enron corpus, and there are other cases where Clojure/Duckling itself is crashing, because it reaches some max size. I also confirmed that this happens when calling directly from Duckling.

Thanks for maintaining this library and being so responsive :-)

**Comment by FraBle** [comment]
Hi Chris, cool, I will close the issue then.

For the crashing problems, you may be able to fix them by increasing the JVM memory settings.

No problem :)
