### ISSUE TITLE
Duckling in threaded Django environment

### ISSUE THREAD

**Issue by bduvenhage** [FraBle/python-duckling#15]
Hi FraBle

I’ve applied a fix within my local Duckling (duckling.py around line 108 to allow parsing in a multi-threaded environment. The parse call is coming from a different thread as the one that created the instance and started the JVM.

The code I added just above 'language = …’ around line 108 is:

if threading.activeCount() > 1:
    if jpype.isThreadAttachedToJVM() is not 1:
        jpype.attachThreadToJVM()

It is a snippet from __init__ and seems to solve my problem. However, I don’t really know jpype. Please have a look at the code and let me know if you want me to create a pull request for it.

Kind regards
Bernardt

**Comment by FraBle** [comment]
Fixed with [v1.7.1](https://pypi.python.org/pypi/duckling/1.7.1) :)

**Comment by bduvenhage** [comment]
Thank you!
