### ISSUE TITLE
Duckling compatibility with Python 3

### ISSUE THREAD

**Issue by bduvenhage** [FraBle/python-duckling#16]
Hi 

Not sure why, but a day or two ago duckling.py stopped working on Python 3 system due to types.StringType on line 140. I've been using Python 3 for a while, but only gotten this problem now.

Would it make sense to change line 140 to `if isinstance(dim_filter, string_types):` to use the string type from six instead of StringType from types?

Regards
Bernardt

**Comment by FraBle** [comment]
Thanks for noticing, fixed it, on master, will release soon. Looking into the multi-threading issue with Flask/Django right now.

**Comment by FraBle** [comment]
Fixed with [v1.7.1](https://pypi.python.org/pypi/duckling/1.7.1) :)

**Comment by bduvenhage** [comment]
Awesome!. Thanks.
