### ISSUE TITLE
duckling 0.2.23 downgrade

### ISSUE THREAD

**Issue by oziee** [FraBle/python-duckling#19]
i still get messages in the log.. but only two line:) not the lots of ?????? lines

"not found" "san silvestro"
"not found" "notte di san silvestro"

and I'm using en files so not sure why its logging Italian info about new years eve etc:)

**Comment by FraBle** [comment]
That's really odd. Can you give me a code example?
With the latest Duckling I got the "not found" messages for Hebrew.
Apparently, this happens when the tests fail when Duckling loads.

**Comment by oziee** [comment]
emailed

**Comment by FraBle** [comment]
Closing since it's a Duckling issue.
