### ISSUE TITLE
python-sutime seems to interfere with python-duckling

### ISSUE THREAD

**Issue by savvopoulos** [FraBle/python-duckling#2]
Hi, as soon as I added your other lib:
https://github.com/FraBle/python-sutime

I got:
Traceback (most recent call last):
  File "step_1_gen_input.py", line 137, in <module>
    main(sys.argv[1:])
  File "step_1_gen_input.py", line 127, in main
    jmaps = get_dataset(fpaths, args.n)
  File "step_1_gen_input.py", line 43, in get_dataset
    d = duckling.DucklingWrapper()
  File "/usr/local/lib/python3.5/site-packages/duckling/wrapper.py", line 23, in **init**
    jvm_started=jvm_started, parse_datetime=parse_datetime)
  File "/usr/local/lib/python3.5/site-packages/duckling/duckling.py", line 45, in **init**
    self.clojure = jpype.JClass('clojure.java.api.Clojure')
  File "/usr/local/lib/python3.5/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class clojure.java.api.Clojure not found

Removing it makes the issue go away.

**Comment by savvopoulos** [comment]
Code in question.

from sutime import SUTime
jars = os.path.join(os.path.dirname(__file__), 'jars')
sutime = SUTime(jars, mark_time_ranges=True)

import duckling
d = duckling.DucklingWrapper()

**Comment by savvopoulos** [comment]
Note that reversing the order causes the opposite problem:

Traceback (most recent call last):
  File "step_1_gen_input.py", line 21, in <module>
    sutime = SUTime(jars, mark_time_ranges=True)
  File "/usr/local/lib/python3.5/site-packages/sutime/sutime.py", line 57, in __init__
    'edu.stanford.nlp.python.SUTimeWrapper')
  File "/usr/local/lib/python3.5/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class edu.stanford.nlp.python.SUTimeWrapper not found

**Comment by FraBle** [comment]
Hi Chris,

It's possible to use both libraries together. I do it myself for a project with my company.
Both packages provide an optional boolean parameter `jvm_started`, which indicates that you already started JVM via jpype (with all necessary JAR files) from outside.
Something like this:
```python
#!/usr/bin/env python
from java import JavaConnector
import os
from sutime import SUTime
from duckling import DucklingWrapper

if __name__ == '__main__':
    # get the path to all jar files
    jar_files = os.path.join(os.path.dirname(__file__), 'jars')

    # start our own JVM with all Java dependencies
    java_connector = JavaConnector(jars=jar_files)
    java_connector.start()

    # create SUTime object with the information, that the JVM is already
    # started
    sutime = SUTime(
        jvm_started=True, mark_time_ranges=True)
    print(sutime.parse('I need a desk for tomorrow from 2pm for 2 hours'))

    # create DucklingWrapper object with the information, that the JVM is
    # already started
    duckling = DucklingWrapper(
        jvm_started=True, parse_datetime=True)
    print(duckling.parse_time('Let\'s meet at 11:45am'))
```

with JavaConnector looking like this (I may create a package out of this):
```python
import os
import threading
import jpype
import socket

socket.setdefaulttimeout(15)


class JavaConnector(object):

    _required_jars = {
        'clj-time-0.8.0.jar',
        'clojure-1.8.0.jar',
        'duckling-0.4.16.jar',
        'ejml-0.23.jar',
        'gson-2.7.jar',
        'javax.json-api-1.0.jar',
        'jaxb-api-2.2.7.jar',
        'joda-time-2.3.jar',
        'joda-time-2.9.jar',
        'jollyday-0.4.7.jar',
        'lazymap-3.1.0.jar',
        'plumbing-0.5.3.jar',
        'schema-1.0.1.jar',
        'slf4j-api-1.7.12.jar',
        'slf4j-simple-1.7.21.jar',
        'stanford-corenlp-3.6.0-models.jar',
        'stanford-corenlp-3.6.0.jar',
        'stanford-corenlp-sutime-python-1.0.0.jar',
        'tools.logging-0.2.6.jar',
        'xalan-2.7.0.jar',
        'xercesImpl-2.8.0.jar',
        'xml-apis-1.3.03.jar',
        'xom-1.2.10.jar'
    }

    def __init__(self, jars=''):
        super(JavaConnector, self).__init__()
        self.jars = jars
        self._classpath = self._create_classpath()
        self._lock = threading.Lock()

    def start(self):

        self._start_jvm()
        if threading.activeCount() > 1:
            if jpype.isThreadAttachedToJVM() is not 1:
                jpype.attachThreadToJVM()

    def _start_jvm(self):
        if jpype.isJVMStarted() is not 1:
            jpype.startJVM(jpype.getDefaultJVMPath(
            ), '-Djava.class.path={classpath}'.format(classpath=self._classpath))

    def _create_classpath(self):
        jars = []
        jar_file_names = []
        for top, dirs, files in os.walk(self.jars):
            for file_name in files:
                if file_name.endswith('.jar'):
                    jars.append(os.path.join(top, file_name))
                    jar_file_names.append(file_name)
        if not JavaConnector._required_jars.issubset(jar_file_names):
            raise RuntimeError(
                'Not all necessary Java dependencies have been downloaded!')
        return os.pathsep.join(jars)
```

**Comment by savvopoulos** [comment]
thanks

**Comment by savvopoulos** [comment]
PS Could you include your pom.xml for the required jars above? :) thanks
