### ISSUE TITLE
Timezone mismatch with reference_time

### ISSUE THREAD

**Issue by vinvinod** [FraBle/python-duckling#20]
I am seeing that the timezone set with `reference_time` is not being returned in the result.
Here is the example
``` python
>>> import duckling
>>> import pprint
>>> d = duckling.DucklingWrapper()
>>> pprint.pprint(d.parse_time('today at 2 pm', reference_time='2017-05-28T00:00:00+05:30'))
[{u'dim': u'time',
  u'end': 13,
  u'start': 0,
  u'text': u'today at 2 pm',
  u'value': {u'others': [u'2017-05-28T14:00:00.000+05:00'],
             u'value': u'2017-05-28T14:00:00.000+05:00'}}]
```
Though I am using the timezone `+05:30` the result has `+05:00`
I am using version `1.7.1`

**Comment by FraBle** [comment]
Hi @vinvinod, this is a (known) issue with Duckling itself: 
https://github.com/wit-ai/duckling_old/issues/209

**Comment by vinvinod** [comment]
Thanks @FraBle
