### ISSUE TITLE
Seg fault on ubuntu 14.04 (3.13 kernel) not on 16.04 (4.4.0 kernel)

### ISSUE THREAD

**Issue by milutz** [FraBle/python-duckling#23]
I'm seeing something that appears to be a kernel interaction with python-duckling - here are the steps to illustrate/reproduce:

Spinning up a (Digital Ocean defined) default ubuntu 14.04.5 x64 (3.13.0-121 kernel) image on 4Gig ram, two core Digital Ocean "droplet", and installing Ducking with the following:
```
apt-get update ; apt-get install -y --no-install-recommends build-essential git-core default-jre python-pip python-dev python-setuptools ; pip install duckling
```

### On ubuntu 14.04 (3.13 kernel)
Duckling instance that **Segmentation Faults**:
```
# python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckling
>>> d= duckling.DucklingWrapper()
Segmentation fault (core dumped)
#
```

### On ubuntu 16.04 (4.4.0 kernel)
Repeating the same on Digital Ocean Ubuntu 16.04.2 x64 creates an instance that **works**:
```
# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckling
>>> d= duckling.DucklingWrapper()
>>> print(d.parse_time(u'Let\'s meet at 11:45am'))
[{u'dim': u'time', u'end': 21, u'start': 11, u'value': {u'grain': u'minute', u'value': u'2017-07-26T11:45:00.000Z', u'others': [{u'grain': u'minute', u'value': u'2017-07-26T11:45:00.000Z'}, {u'grain': u'minute', u'value': u'2017-07-27T11:45:00.000Z'}, {u'grain': u'minute', u'value': u'2017-07-28T11:45:00.000Z'}]}, u'text': u'at 11:45am'}]
>>> 
```
(`d= duckling.DucklingWrapper()` took about 30 secs to return)

### On ubuntu 14.04 force loaded to have 4.4.0 kernel
Retrying on 14.04 but updating kernel (4.4.0-87) also **works**: 
( kernel update cmd from https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Server-1 )
```
# apt-get install --install-recommends linux-generic-lts-xenial
[...bunch of output...]
# reboot
[... re-login...]
# python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckling
>>> d= duckling.DucklingWrapper()
"not found" "san silvestro"
"not found" "notte di san silvestro"
>>> print(d.parse_time(u'Let\'s meet at 11:45am'))
[{u'dim': u'time', u'end': 21, u'start': 11, u'value': {u'grain': u'minute', u'value': u'2017-07-26T11:45:00.000Z', u'others': [{u'grain': u'minute', u'value': u'2017-07-26T11:45:00.000Z'}, {u'grain': u'minute', u'value': u'2017-07-27T11:45:00.000Z'}, {u'grain': u'minute', u'value': u'2017-07-28T11:45:00.000Z'}]}, u'text': u'at 11:45am'}]
>>>
```
(`d= duckling.DucklingWrapper()` took about 30 secs to return)
(while the results seem correct, the object instantiation seems to be triggering issue https://github.com/wit-ai/duckling_old/issues/210)

### Ubuntu 14.04 matters for Docker Cloud
I'm specifically interested in ubuntu 14.04/3.13-kernel because Docker containers deployed under the Docker Cloud/Cluster automated environment (when you see the "[whale] Deploy to Cloud" button in Github projects) _only_ runs ubuntu 14.04/3.13-kernal hosts.  So I'm unable to use python-duckling in Docker Cloud auto deployment system today.

**Comment by FraBle** [comment]
That is very weird behavior. I assume it could be an issue with [JPype ](https://github.com/originell/jpype/) or the Java runtime running Clojure.
Can you try to run the Java code directly, that I described for example in https://github.com/FraBle/python-duckling/issues/25#issuecomment-323574059

**Comment by FraBle** [comment]
I tried to reproduce it with a VirtualBox VM from [OSboxes](https://www.osboxes.org/ubuntu/#ubuntu-14_04-info) and by downgrading its kernel to 3.13. The installation of JPype throws some warnings, but it does not result in a segmentation fault.
