### ISSUE TITLE
Money Parsing Error

### ISSUE THREAD

**Issue by jithurjacob** [FraBle/python-duckling#25]
Hi Guys,

For me, **_1 million dollar_** and **_0.1 million dollar_** are returning same response. I had raised an [issue](https://github.com/facebookincubator/duckling/issues/81#event-1205212348) at Duckling Repo and the Dev team has confirmed that issue is with the Python library. Could you please update the library?

Version Info

Name: duckling
Version: 1.7.2

**Comment by FraBle** [comment]
I wrote the following little Java program to test the behaviour of Duckling:
```java
package com.duckling.million;


import clojure.java.api.Clojure;
import clojure.lang.IFn;
import clojure.lang.LazySeq;
import clojure.lang.PersistentArrayMap;

public class DucklingTest {

    private static final IFn require = Clojure.var("clojure.core", "require");
    private static final IFn load = Clojure.var("duckling.core", "load!");
    private static final IFn parse = Clojure.var("duckling.core", "parse");

    public static void main(String[] args) {
        require.invoke(Clojure.read("duckling.core"));
        load.invoke();
        
        LazySeq results = (LazySeq) parse.invoke(
                "en$core", "0.1 million dollar", Clojure.read("[:amount-of-money]"));
        
        PersistentArrayMap result = (PersistentArrayMap) results.first();
        PersistentArrayMap value = (PersistentArrayMap) result.valAt(Clojure.read(":value"));
        
        System.out.printf("Type: %s\nValue: %s\nUnit: %s",
                value.valAt(Clojure.read(":type")),
                value.valAt(Clojure.read(":value")),
                value.valAt(Clojure.read(":unit")));
    }
}
```

Even with the latest version of Duckling (`0.4.24`) it prints out:
```
Type: value
Value: 1000000
Unit: $
```
I ran it on macOS Sierra with Oracle Java 1.8.0_141.

One important note: You raised the issue in the [reimplemented version of Duckling in Haskell](https://github.com/facebookincubator/duckling). However, this wrapper was developed for the [original Clojure version of Duckling](https://github.com/wit-ai/duckling_old).
The answer from the Duckling team in your linked issue sends a request against the new Haskell version.

**Comment by jithurjacob** [comment]
@FraBle Are we planning on migrating to the new Haskell version?

**Comment by FraBle** [comment]
Calling Haskell from Python is unfortunately way more complex than calling Clojure through Java from Python. Another option (and easier) would be to wrap the HTTP server that Duckling provides.
However, I couldn't find the time yet to look further into this. But please feel free to start a new wrapper for the Duckling Haskell-version :)

**Comment by jithurjacob** [comment]
I'll try to build one :)
