### ISSUE TITLE
Giving all the possible dimensions and values 

### ISSUE THREAD

**Issue by balaram-bhukya** [FraBle/python-duckling#26]
d1.parse('i need to earn 100k dollars')  it gives 

[{'dim': 'number', 'text': '100k', 'start': 12, 'end': 16, 'value': {'value': 100000.0}}, {'dim': 'time', 'text': '100', 'start': 12, 'end': 15, 'value': {'value': '0100-01-01T00:00:00.000+05:53:28', 'grain': 'year', 'others': []}}, {'dim': 'amount-of-money', 'text': '100k dollars', 'start': 12, 'end': 24, 'value': {'value': 100000.0, 'unit': '$'}}, {'dim': 'distance', 'text': '100k', 'start': 12, 'end': 16, 'value': {'value': 100.0, 'unit': 'kilometre'}}, {'dim': 'volume', 'text': '100k', 'start': 12, 'end': 16, 'value': {'value': 100000.0, 'unit': None, 'latent': True}}, {'dim': 'temperature', 'text': '100k', 'start': 12, 'end': 16, 'value': {'value': 100000.0, 'unit': None}}]

but i need only 

# **{'dim': 'amount-of-money', 'text': '100k dollars', 'start': 12, 'end': 24, 'value': {'value': 100000.0, 'unit': '$'}},**

**Comment by FraBle** [comment]
You could either use `parse_money()` from the `DucklingWrapper` ([example in the tests](https://github.com/FraBle/python-duckling/blob/master/duckling/test/test_duckling_wrapper.py#L236)) or specify a `dim_filter` for `Duckling` ([example in the tests](https://github.com/FraBle/python-duckling/blob/master/duckling/test/test_duckling.py#L315))
