### ISSUE TITLE
Installation error with Docker

### ISSUE THREAD

**Issue by Tpt** [FraBle/python-duckling#27]
When trying to install the latest version of Duckling with the Docker `python:3-stretch` image with JDK8 installed I get the following error:

```
ISearching for duckling
Reading https://pypi.python.org/simple/duckling/
No local packages or working download links found for duckling
error: Could not find suitable distribution for Requirement.parse('duckling')
```

Not sure what could be the root cause of this error.

**Comment by FraBle** [comment]
I created the following `Dockerfile` to test it:
```Dockerfile
FROM python:3-stretch

# Install Java.
RUN \
  apt-get update && \
  apt-get install -y default-jre && \
  rm -rf /var/lib/apt/lists/*

# Define working directory.
WORKDIR /data

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN pip install duckling

# Define default command.
CMD ["python"]
```

I ran `docker build -t duckling:latest .` and started the container by executing `docker run -it duckling:latest`. This gave me a running Python interpreter and I could execute the following code successfully:
```
>>> import duckling
>>> d = duckling.DucklingWrapper()
>>> print(d.parse_time('connect today'))
```
