### ISSUE TITLE
Problem in Django multi threaded environment

### ISSUE THREAD

**Issue by manohar1989** [FraBle/python-duckling#29]
According the fix for multi threaded environment:
if threading.activeCount()>1
in init method, It is checking for 2nd thread which is creating the same class's object.
But what if I have only one object which is shared by all threads? It is failing in this case because one thread is creating it and rest all are using it.
So I removed this check. I am not sure of the consequences, please suggest.

**Comment by FraBle** [comment]
Hi @manohar1989, can you give some example code?
Please also check out the latest version (`1.8.0`).

**Comment by FraBle** [comment]
Closed due to inactivity.
