### ISSUE TITLE
python-duckling doesn't return "grain"

### ISSUE THREAD

**Issue by savvopoulos** [FraBle/python-duckling#3]

**Comment by savvopoulos** [comment]
clojure output:
`({:dim :time, :body "tomorrow", :value {:type "value", :value "2016-11-02T00:00:00.000Z", :grain :day, :values ({:type "value", :value "2016-11-02T00:00:00.000Z", :grain :day})},`

python output:
`[{'end': 14, 'dim': 'time', 'text': 'tomorrow', 'value': {'value': '2016-11-02T00:00:00.000Z', 'others': ['2016-11-02T00:00:00.000Z']}, 'start': 6}, {'end': 5, 'dim': 'time', 'text': 'lunch', 'value': {'value': {'to': '2016-11-01T14:00:00.000Z', 'from': '2016-11-01T12:00:00.000Z'}, 'others': [{'to': '2016-11-01T14:00:00.000Z', 'from': '2016-11-01T12:00:00.000Z'}, {'to': '2016-11-02T14:00:00.000Z', 'from': '2016-11-02T12:00:00.000Z'}, {'to': '2016-11-03T14:00:00.000Z', 'from': '2016-11-03T12:00:00.000Z'}]}, 'start': 0}]`

**Comment by savvopoulos** [comment]
This can be fixed by using the low level version:
    d = Duckling()
    d.load() # always load the model first
    print(d.parse('tomorrow'))
    # [{u'body': u'tomorrow', u'dim': u'time', u'end': 8, u'value': {u'values': [{u'grain': u'day', u'type': u'value', u'value': u'2016-10-10T00:00:00.000-07:00'}], u'grain': u'day', u'type': u'value', u'value': u'2016-10-10T00:00:00.000-07:00'}, u'start': 0}]

**Comment by FraBle** [comment]
I integrated grain now into the wrapper as well. I twill return something like
```json
    {
        "dim": "time",
        "end": 23,
        "start": 6,
        "text": "for 2 hours today",
        "value": {
            "grain": "minute",
            "others": [
                {
                    "grain": "minute",
                    "value": "2017-05-09T16:56:00.000-07:00"
                }
            ],
            "value": "2017-05-09T16:56:00.000-07:00"
        }
    }
```
