### ISSUE TITLE
Problems after update to JPype1 0.6.3

### ISSUE THREAD

**Issue by bduvenhage** [FraBle/python-duckling#31]
Hi 

After updating to latest JPype1 (0.6.3) I had a problem with some of my unit tests that included Duckling and I had to make a modification in duckling.py _start_jvm(...)

The modification was to change on line 67:
`if jpype.isJVMStarted() is not 1:` to `if jpype.isJVMStarted() is False:`
(https://github.com/FraBle/python-duckling/blob/f25a214363f07be205bbf2a74ce4e0557b126c32/duckling/duckling.py#L67)

This makes sense since jpype.isJVMStarted() seems to return True/False. 

This one change fixed my problem. However, since jpype.isThreadAttachedToJVM() seems to also return True/False and both methods are used in various places in the code, there might be more places that this needs to be fixed.

Kind regards
Bernardt

**Comment by FraBle** [comment]
I found the necessary changes (basically what you described) and will release a patch version soon.

**Comment by FraBle** [comment]
It should be fixed now with [`duckling v1.8.0`](https://pypi.python.org/pypi/duckling/1.8.0).
