### ISSUE TITLE
parse_time issue

### ISSUE THREAD

**Issue by prateekchoudhary** [FraBle/python-duckling#33]
`print(d.parse_time(u'list top 20 customers in last 10 days'))
`

Output : 

`[{'dim': 'time', 'text': 'last 10 days', 'start': 25, 'end': 37, 'value': {'value': {'to': '2018-05-02T00:00:00.000+05:30', 'from': '2018-04-22T00:00:00.000+05:30'}, 'others': []}}, {'dim': 'time', 'text': '20', 'start': 9, 'end': 11, 'value': {'value': '2018-05-02T20:00:00.000+05:30', 'grain': 'hour', 'others': [{'grain': 'hour', 'value': '2018-05-02T20:00:00.000+05:30'}, {'grain': 'hour', 'value': '2018-05-03T20:00:00.000+05:30'}, {'grain': 'hour', 'value': '2018-05-04T20:00:00.000+05:30'}]}}]`

However, If I change the string to the following, the output comes fine:

`print(d.parse_time(u'list top customers in last 10 days'))
`

Output:

`[{'dim': 'time', 'text': 'last 10 days', 'start': 8, 'end': 20, 'value': {'value': {'to': '2018-05-02T00:00:00.000+05:30', 'from': '2018-04-22T00:00:00.000+05:30'}, 'others': []}}]`

Why does the same query 'list top 20 customers by sales in last 10 days' seem to work fine on [duckling.wit.ai](https://duckling.wit.ai/)

**Comment by prateekchoudhary** [comment]
Update: This is a duckling(Clojure version) issue. The updated Duckling (Haskell version) seems to have resolved this : [https://github.com/facebook/duckling/issues/157](url). I am closing this for now. Thanks

**Comment by FraBle** [comment]
Thanks for looking into this and updating the GitHub issue!
