### ISSUE TITLE
python-duckling doesn't have a context param

### ISSUE THREAD

**Issue by savvopoulos** [FraBle/python-duckling#4]
In my case, being able to pass a reference time would massively simplify writing tests.

**Comment by savvopoulos** [comment]
Hi, I recently noticed that this was resolved for python-sutime. Would be great to have it for python-duckling too!

**Comment by FraBle** [comment]
Working on it right now, sorry for the delay!

**Comment by FraBle** [comment]
@savvopoulos, can you provide an example on how to pass a reference date in the context to Duckling in Clojure?

**Comment by savvopoulos** [comment]
Hi Frank

Thanks for looking into this. Here is an example:
(p/parse :en$core snippet [:time] {:reference-time (parse-iso-time
ref-date)})

where:
* p is: (:require [duckling.core :as p])
* snippet is the string being parsed
* ref-date is the reference date, constructed like this:
  (defn parse-iso-time [iso-str]
    (let [t (time/parse (time/formatters :date-time) iso-str)]
      (dt/t
        0 (.getYear t) (.getMonthOfYear t) (.getDayOfMonth t)
        (.getHourOfDay t) (.getMinuteOfHour t) 0)))
* dt is: (:require [duckling.time.obj :as dt])

**Comment by FraBle** [comment]
After hours of fighting aginst the Clojure Java Interop, I finally managed to provide the parameter for a reference time.
I have published the latest version (1.2.1) and you can install it via pip.

Here is how to use it:
```python
    duckling_wrapper = DucklingWrapper()
    print(json.dumps(duckling_wrapper.parse(u'today', reference_time='1990-12-30')))

    duckling = Duckling()
    duckling.load()
    print(duckling.parse(u'today', reference_time='1990-12-30'))
```

**Comment by FraBle** [comment]
One additional note:
Duckling seems to have problems with utc offsets, that are not full hours.
I opened an issue here: https://github.com/wit-ai/duckling/issues/209

**Comment by savvopoulos** [comment]
Amazing - being waiting for this. Thank you so much :-) 👍
